### PR TITLE
Fix line endings

### PR DESCRIPTION
**Pull request by fsfod**
Fix line endings in benchmarks, krun and simplerunner

### CODE REVIEW

**Comment by ltratt** [comment]
Does this PR also chop off trailing spaces at the end of lines? I noticed quite a lot of those earlier too. Might as well use this opportunity...

**Comment by fsfod** [comment]
@ltratt I went and trimmed all the trailing space

**Comment by ltratt** [comment]
Excellent! If you squash, I can merge.

**Comment by fsfod** [comment]
@ltratt squashed and ready to merge

**Pull request merged**
