### PR TITLE
Add a benchmark based on the moonscript compiler

### PR DESCRIPTION
**Pull request by fsfod**
Add a large benchmark based on the moonscript compiler that transpiles .moon files to Lua. Currently I'm just compiling the moonscript compiler's own source code as the benchmark. The compiler also has linting mode that could maybe be another benchmark.
Travis also fails on RaptorJIT for moonscript because of the missing shared Lua lib issue.

### CODE REVIEW

**Comment by ltratt** [comment]
How big is this benchmark in KiB? And how many of the files are slurped in verbatim? It would surely be better (from our POV) to download this benchmark in the build script and move files into the right place? Also, what's the benchmark's license?

**Comment by fsfod** [comment]
There is not really a benchmark in moonscript repo i just built one based on very clean API's the compiler was calling [parse.string](https://github.com/leafo/moonscript/blob/master/moonscript/cmd/moonc.lua#L68 ) and [compile.tree](https://github.com/leafo/moonscript/blob/master/moonscript/cmd/moonc.lua#L92).

The source .moon files I'm compiling for the benchmark are only 150kb that will only be about 40kb in git's storage and I had already separated out source files from everything else in the moonscript repo. Also i already fetch the compiler using Lua Rocks.

The licence of the moonscript compiler is MIT like most Lua libraries.

**Comment by ltratt** [comment]
Have any of the `.moon` files been changed at all?

**Comment by fsfod** [comment]
Well they were unmodified from the moonscript repo

**Comment by fsfod** [comment]
@ltratt I squashed it away

**Comment by fsfod** [comment]
@ltratt ready to merge

**Pull request merged**
