### PR TITLE
Add jitstats collection to the benchmarks

### PR DESCRIPTION
**Pull request by fsfod**
Add JIT stats instrumentation to the benchmarks when under krun using a modified iterations_runner.lua that collects stats for each iteration and prints them stderror as json like existing runners did.

### CODE REVIEW

**Comment by vext01** [comment]
This looks OK to me.

It's a shame that we have had to fragment from Krun, but on the upside, we can always integrate these changes later if we find a practical way to do so.

Can you show us what the instrumentation data looks like?

**Comment by ltratt** [comment]
I also think we should see a combined plot. It might need some help from @snim2 to do this.

**Comment by snim2** [comment]
I've probably missed something obvious but what's a combined plot?

**Comment by fsfod** [comment]
This is from only testing with two iterations.
```json
{
	"jitstats": [{
			"abort_counts": {
				"DOWNREC": 2005,
				"LUNROLL": 810,
				"NYIBC": 3660,
				"TYPEINS": 49,
				"LINNER": 3271,
				"CUNROLL": 79,
				"MCODEAL": 30,
				"LLEAVE": 1548
			},
			"linktypes": {
				"return": 1810,
				"stitch": 1094,
				"up-recursion": 8,
				"interpreter": 958,
				"root": 10201,
				"down-recursion": 12,
				"loop": 1016
			},
			"stitch_starts": 896,
			"exits": 171455,
			"traceflush": 30,
			"side_starts": 17415,
			"side_completed": 12186,
			"stitch_aborts": 109,
			"starts": 26551,
			"stitch_completed": 787,
			"side_aborts": 5229,
			"loop_blacklisted": 0,
			"nyi_bc": {
				"FNEW": 2,
				"VARG": 1155,
				"UCLO": 2,
				"ISNEXT": 1904,
				"ITERN": 597
			},
			"func_blacklisted": 0,
			"aborts": 11452,
			"completed": 15099
		}, {
			"abort_counts": {
				"DOWNREC": 1926,
				"LUNROLL": 858,
				"NYIBC": 3417,
				"TYPEINS": 70,
				"LINNER": 3259,
				"CUNROLL": 101,
				"MCODEAL": 29,
				"LLEAVE": 1567
			},
			"linktypes": {
				"return": 1740,
				"stitch": 966,
				"up-recursion": 6,
				"interpreter": 948,
				"root": 9909,
				"down-recursion": 14,
				"loop": 990
			},
			"stitch_starts": 810,
			"exits": 165022,
			"traceflush": 29,
			"side_starts": 16816,
			"side_completed": 11782,
			"stitch_aborts": 87,
			"starts": 25800,
			"stitch_completed": 723,
			"side_aborts": 5034,
			"loop_blacklisted": 0,
			"nyi_bc": {
				"FNEW": 2,
				"VARG": 1061,
				"UCLO": 2,
				"ITERN": 546,
				"ISNEXT": 1806
			},
			"func_blacklisted": 0,
			"aborts": 11227,
			"total": {
				"abort_counts": {
					"DOWNREC": 3931,
					"LUNROLL": 1668,
					"NYIBC": 7077,
					"TYPEINS": 119,
					"LINNER": 6530,
					"CUNROLL": 180,
					"MCODEAL": 59,
					"LLEAVE": 3115
				},
				"linktypes": {
					"return": 3550,
					"stitch": 2060,
					"up-recursion": 14,
					"interpreter": 1906,
					"root": 20110,
					"down-recursion": 26,
					"loop": 2006
				},
				"stitch_starts": 1706,
				"exits": 336477,
				"traceflush": 59,
				"side_starts": 34231,
				"side_completed": 23968,
				"stitch_aborts": 196,
				"starts": 52351,
				"stitch_completed": 1510,
				"side_aborts": 10263,
				"loop_blacklisted": 0,
				"nyi_bc": {
					"FNEW": 4,
					"VARG": 2216,
					"UCLO": 4,
					"ITERN": 1143,
					"ISNEXT": 3710
				},
				"func_blacklisted": 0,
				"aborts": 22679,
				"completed": 29672
			},
			"completed": 14573
		}
	]
}

```

**Comment by ltratt** [comment]
Prints things like compilation time etc.

**Comment by fsfod** [comment]
> It's a shame that we have had to fragment from Krun, but on the upside, we can always integrate these changes later if we find a practical way to do so.

The modified runner can work standalone of any extra lua modules if instrumentation is turned off.

**Comment by vext01** [comment]
There's a lot of good stats in there Tom, nice one! Totally worth having them per-in-process-iteration too!

**Comment by vext01** [comment]
@snim2 instrumentation plots. But now you have lots of new kinds of metrics. I suppose the plot script will need ammending (the horror!).

**Comment by ltratt** [comment]
True. OK, we shouldn't hold this PR up while that's in progress. So I suggest you view this PR in isolation @vext01.

**Comment by vext01** [comment]
@ltratt are you OK with the divergence from Krun. That is my only concern.

**Comment by ltratt** [comment]
Divergence?

**Comment by vext01** [comment]
Tom has had to define his own vm def and iterations runner (in his repo) to achieve his goal.

**Comment by snim2** [comment]
So, to plot new instrumentation data, you need to add a new instrumentation class to this module:

https://github.com/softdevteam/warmup_experiment/blob/master/warmup/vm_instruments.py

to parse the new JSON. As with all these scripts, the code may not be very obvious (!!!) but it's worth looking at some raw JSON from the existing instrumented VMs to get a feel for how the existing code works.

**Comment by ltratt** [comment]
@vext01 Should this be merged into Krun or ...?

**Comment by vext01** [comment]
The problem is, the jit stats stuff has dependencies, which we would either need to import (license permitting) or add something to the build system to fetch.

Thoughts?

**Comment by ltratt** [comment]
Let's get this PR in now, and next week at the meeting we can discuss whether this is best off in Krun or not.

**Comment by vext01** [comment]
OK :)

@fsfod to you want to squash?

**Comment by fsfod** [comment]
@vext01 squashed

**Pull request merged**
