### PR TITLE
A first attempt at expanding the README.

### PR DESCRIPTION
**Pull request by ltratt**
Please check this carefully -- I may well have got details wrong! Suggestions for additions and  improvements are also welcome!

### CODE REVIEW

**Comment by fsfod** [comment]
quicktest.krun is really more a sanity check it only runs the benchmarks once for one iteration and execution

**Comment by ltratt** [comment]
Point taken. See if that new commit helps.

**Comment by fsfod** [comment]
Thats a better explanation. There should also be some note about Lua modules living in the lualibs folder

**Comment by ltratt** [comment]
I don't know what those are, so you're going to have to explain them to me...

**Comment by fsfod** [comment]
They have to be in that folder because require/module loading is not relative to a script in Lua

**Comment by ltratt** [comment]
Can you propose some text and tell me where you think it should go? I don't really know this well enough.

**Comment by fsfod** [comment]
something like Any extra Lua modules your benchmark needs should go in the 'lualibs' folder

**Comment by ltratt** [comment]
I need more than that. Why would there be extra Lua modules? etc. etc.

**Comment by fsfod** [comment]
because the benchmark might be based on them?

**Comment by ltratt** [comment]
Please can you draft a paragraph that's clear about what you're thinking. I'm not able to guess well enough to do a proper job :/

**Comment by fsfod** [comment]
"If you benchmark depends on any custom Lua modules should put them in the 'lualibs' folder so they are found correctly by 'require'"

**Comment by ltratt** [comment]
Issue https://github.com/softdevteam/lua_benchmarking/issues/24 means that we can more-or-less ignore the shared global dir at the moment. I think that means this PR is ready for squashing/

**Comment by ltratt** [comment]
Ping.

**Comment by fsfod** [comment]
Maybe there should be some note about about using the ffi/ctype system since we do use it it some of the benchmarks

**Comment by ltratt** [comment]
Happy to consider it -- you'll need to suggest draft text for that though.

**Comment by fsfod** [comment]
something like "Some of the existing benchmarks already use LuaJIT's ffi/cdata system so feel free to use it in your own benchmarks if it makes sense"

**Comment by ltratt** [comment]
Hmm, maybe the real thing here is that some benchmarks might need to build libraries (etc.) in order to run. Maybe we should do a (separate) PR that says "benchmarks can have a `build.lua` script which will be run before benchmarking in order to build XYZ"? That would need a bit of thinking about to get the design right, but it might not be the worst idea ever.

**Comment by fsfod** [comment]
I meant cdata system thats part of ffi system but doesn't involve calling out to external code

**Comment by ltratt** [comment]
cdata?

**Comment by fsfod** [comment]
it extra type in LuaJIT that mimics stuff from C like native structs and pointers

**Comment by ltratt** [comment]
I'm sorry, you've completely lost me. How does that relate to the sentence you wrote?

**Comment by fsfod** [comment]
It might be more work than just using shell scripts. Lua does have a module repository system like pip like system called LuaRocks

**Comment by ltratt** [comment]
The code can just call a shell script if it wants. Or we could call `build.sh` in the directory.

OK, I'm going to suggest that I raise an issue to debate this point further. But I think this PR is now ready to be squashed.

**Comment by fsfod** [comment]
@ltratt squash away

**Comment by ltratt** [comment]
Thanks! Squashed.

**Pull request merged**
